In [146]:
import cv2
import rasterio
import numpy as np
import sys
sys.path.append('src')

In [85]:
F0 = cv2.imread("../Images/sim_Landsat_t1.tif")
C0 = cv2.imread("../Images/sim_MODIS_t1.tif")
C1 = cv2.imread("../Images/sim_MODIS_t2.tif")

In [86]:
type(F0)

numpy.ndarray

In [87]:
F0.shape

(150, 150, 3)

In [88]:
windowSize = 3
padAmount = windowSize//2
print(padAmount)

1


In [89]:
padded_F0 = np.pad(F0, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

In [90]:
padded_F0.shape

(152, 152, 3)

In [91]:
F0_test = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [92]:
def padArray(arr, windowSize):
    padAmount = windowSize//2
    return np.pad(arr, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

In [93]:
F0_test.shape

(2, 2, 3)

In [94]:
F0_test.shape

(2, 2, 3)

In [95]:
np.set_printoptions(linewidth=np.inf)

In [96]:
padded_F0_test = padArray(F0_test, 3)

In [97]:
padded_F0_test.shape

(4, 4, 3)

In [98]:
print(padded_F0_test)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 4  5  6]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 7  8  9]
  [10 11 12]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [99]:
print(padAmount)

1


In [100]:
i, j = 1, 1
window = padded_F0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
print(window)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 0  0  0]
  [ 7  8  9]
  [10 11 12]]]


In [101]:
for i in range(padAmount, len(padded_F0_test)-padAmount):
    for j in range(padAmount, len(padded_F0_test[0])-padAmount):
        window = padded_F0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
        print(window)
        print("NEXT WINDOW")
    

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 0  0  0]
  [ 7  8  9]
  [10 11 12]]]
NEXT WINDOW
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]
  [ 0  0  0]]]
NEXT WINDOW
[[[ 0  0  0]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 0  0  0]
  [ 7  8  9]
  [10 11 12]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
NEXT WINDOW
[[[ 1  2  3]
  [ 4  5  6]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
NEXT WINDOW


# TESTING PREDICTION

In [102]:
import cv2
import numpy as np

In [103]:
# Set the size of the moving window in which the search for similar pixels 
# is performed
windowSize = 3

# Set the path where the results should be stored
path = 'STARFM_demo/'

# Set to True if you want to decrease the sensitivity to the spectral distance
logWeight = False

# If more than one training pairs are used, set to True
temp = False

# The spatial impact factor is a constant defining the relative importance of 
# spatial distance (in meters)
# Take a smaller value of the spatial impact factor for heterogeneous regions 
# (e.g. A = 150 m)
spatImp = 150 

# increasing the number of classes limits the number of similar pixels
numberClass = 4

# Set the uncertainty value for the fine resolution sensor
# https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/performance 
uncertaintyFineRes = 0.03

# Set the uncertainty value for the coarse resolution sensor
# https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-3-olci/validation
uncertaintyCoarseRes = 0.03

# Other global variables
mid_idx = (windowSize**2)//2
specUncertainty = np.sqrt(uncertaintyFineRes**2 + uncertaintyCoarseRes**2)
tempUncertainty = np.sqrt(2*uncertaintyCoarseRes**2)

# Set the size of the slices in which to divide the image
# This number should be multiple of the image height and not bigger than it
# Use bigger size for small images
sizeSlices = 150

# The depth of zeros to pad around each numpy array
padAmount = windowSize//2

### Padding array

In [122]:
def padArray(arr, windowSize):
    return np.pad(arr, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

In [123]:
F0_test = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
padded_F0_test = np.pad(F0_test, pad_width=windowSize//2, mode='constant', constant_values=0)


In [125]:
C0_test = np.array([[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
padded_C0_test = np.pad(C0_test, pad_width=windowSize//2, mode='constant', constant_values=0)
padded_C0_test

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
C1_test = np.array([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])
padded_C1_test = np.pad(C1_test, pad_width=windowSize//2, mode='constant', constant_values=0)
padded_C1_test

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 1., 2., 3., 0.],
       [0., 1., 2., 3., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
F1_test = C1_test.copy()
F1_test

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

### Spectral Distance

In [128]:
def spectral_distance(F0_window, C0_window):
    spectral_difference_window = F0_window - C0_window
    spectral_distance_window = 1/(abs(spectral_difference_window) + 1.0)
    return spectral_difference_window, spectral_distance_window

### Temporal Distance

In [129]:
def temporal_distance(C0_window, C1_window):
    temp_difference_window = C1_window - C0_window
    temp_distance_window = 1/(abs(temp_difference_window) + 1.0)
    return temp_difference_window, temp_distance_window

### Spatial Distance

In [130]:
def spatial_distance(F0_window):
    coord = np.sqrt((np.mgrid[0:windowSize,0:windowSize]-windowSize//2)**2)
    spat_dist = np.sqrt(((0-coord[0])**2+(0-coord[1])**2))
    rel_spat_dist = spat_dist/spatImp + 1.0 # relative spatial distance
    rev_spat_dist = 1/rel_spat_dist # relative spatial distance reversed
    flat_spat_dist = np.ravel(rev_spat_dist)
    return flat_spat_dist

### Combination Distance

In [131]:
def combination_distance(spectral_distance_window, temporal_distance_window, spatial_distance_window):
    if logWeight == True:
        spectral_distance_window = np.log(spectral_distance_window+1)
        temporal_distance_window = np.log(temporal_distance_window + 1)
    combination_distance_window = spectral_distance_window*temporal_distance_window*spatial_distance_window
    return combination_distance_window

### Similarity Threshold

In [132]:
def similarity_threshold(F0_window):
    F0_window = np.where(F0_window==0, np.nan, F0_window)

    st_dev = np.nanstd(F0_window, axis=0)

    sim_threshold = st_dev*2/numberClass

    return sim_threshold

### Similarity Pixels

In [133]:
def similarity_pixels(F0_window):
    sim_threshold = similarity_threshold(F0_window)
    similar_pixels = np.where(abs(F0_window - F0_window[mid_idx]) <= sim_threshold, 1, 0) 

    return similar_pixels

### Filtering

In [134]:
def filtering(F0_window, spectral_distance_window, temporal_distance_window, spectral_difference_window, temporal_difference_window):
    similar_pixels = similarity_pixels(F0_window)

    max_spec_dist = abs(spectral_difference_window)[mid_idx] + specUncertainty + 1
    max_temp_dist = abs(temporal_difference_window)[mid_idx] + tempUncertainty + 1  

    spec_filter = np.where(spectral_distance_window>1.0/max_spec_dist, 1, 0)

    st_filter = spec_filter

    if temp == True:
        temp_filter = np.where(temporal_distance_window>1.0/max_temp_dist, 1, 0)
        st_filter = spec_filter*temp_filter

    similar_pixels = similar_pixels*st_filter
    return similar_pixels

### Weights

In [140]:
def weighting(spec_dist, temp_dist, comb_dist, similar_pixels_filtered):
    # Assign max weight (1) when the temporal or spectral distance is zero

    zero_spec_dist = np.where(spec_dist[mid_idx] == 1, 1, 0)
    
    zero_temp_dist = np.where(temp_dist[mid_idx] == 1, 1, 0)

    zero_dist_mid = np.where((zero_spec_dist == 1), zero_spec_dist, zero_temp_dist)

    shape = np.subtract(spec_dist.shape,(0,1))

    zero_dist = np.zeros(shape[1])

    zero_dist = np.insert(zero_dist, [mid_idx], zero_dist_mid, axis=0)

    weights = np.where((np.sum(zero_dist) == 1), zero_dist, comb_dist)

    # Calculate weights only for the filtered spectrally similar pixels
    weights_filt = weights*similar_pixels_filtered
    
    # Normalize weights
    norm_weights = weights_filt/(np.sum(weights_filt))                        
    # print ("Done weighting!", norm_weights)
    
    return norm_weights

## Prediction

In [142]:
F0_important_pixels = {}
for i in range(padAmount, len(padded_F0_test)-padAmount):
    for j in range(padAmount, len(padded_F0_test[0])-padAmount):
        F0_important_pixels[(i, j)] = padded_F0_test[i-windowSize//2:i+windowSize//2 + 1, j-windowSize//2:j+windowSize//2 + 1].flatten()
for i, j in F0_important_pixels.keys():
    F0_window = F0_important_pixels[(i, j)]
    C0_window = padded_C0_test[i-windowSize//2:i+windowSize//2 + 1, j-windowSize//2:j+windowSize//2 + 1].flatten()
    C1_window = padded_C1_test[i-windowSize//2:i+windowSize//2 + 1, j-windowSize//2:j+windowSize//2 + 1].flatten()

    # Spectral Difference/Distance
    spectral_difference_window, spectral_distance_window = spectral_distance(F0_window, C0_window)

    # Temporal Difference/Distance
    temporal_difference_window, temporal_distance_window = temporal_distance(C0_window, C1_window)

    # Spatial Distance
    spatial_distance_window = spatial_distance(F0_window)

    # Combination Distance
    combination_distance_window = combination_distance(spectral_distance_window, temporal_distance_window, spatial_distance_window)

    similar_pixels_window = filtering(F0_window, spectral_distance_window, temporal_distance_window, spectral_difference_window, temporal_difference_window)

    weights = weighting(spectral_distance_window, temporal_distance_window, combination_distance_window, similar_pixels_window)

    pred_refl = F0_window + temporal_difference_window
    weighted_pred_refl = np.sum(pred_refl*weights)   
    
    F1_test[i-padAmount][j-padAmount] = weighted_pred_refl
F1_test




array([[ 1.        ,  3.        ,  5.        ],
       [ 4.        ,  4.57414449,  6.71733967],
       [ 7.        ,  9.        , 11.        ]])

### Write a numpy array to a tiff file

In [161]:
product = rasterio.open("../Images/sim_Landsat_t1.tif")
profile = product.profile
profile.update(dtype='float64', count=1, width=3, height=3) # number of bands
file_name = '../results/' + 'prediction.tif'
result = rasterio.open(file_name, 'w', **profile)
result.write(F1_test, 1)
result.close()

/Users/shubhrosesingh/Library/Caches/pypoetry/virtualenvs/mystarfm-sxmhv0iY-py3.10/lib/python3.10/site-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/Users/shubhrosesingh/Library/Caches/pypoetry/virtualenvs/mystarfm-sxmhv0iY-py3.10/lib/python3.10/site-packages/rasterio/__init__.py:314: NotGeoreferencedWarning: The given matrix is equal to Affine.identity or its flipped counterpart. GDAL may ignore this matrix and save no geotransform without raising an error. This behavior is somewhat driver-specific.
  dataset = writer(


## Paper Link
https://opus.bibliothek.uni-augsburg.de/opus4/frontdoor/deliver/index/docId/78805/file/STARFM_paper.pdf

In [163]:
product = rasterio.open("../results/prediction.tif").read(1)
product

array([[ 1.        ,  3.        ,  5.        ],
       [ 4.        ,  4.57414449,  6.71733967],
       [ 7.        ,  9.        , 11.        ]])