In [2]:
import cv2
import numpy as np

In [3]:
F0 = cv2.imread("../Images/sim_Landsat_t1.tif")
C0 = cv2.imread("../Images/sim_MODIS_t1.tif")
C1 = cv2.imread("../Images/sim_MODIS_t2.tif")

In [4]:
type(F0)

numpy.ndarray

In [5]:
F0.shape

(150, 150, 3)

In [6]:
windowSize = 3
padAmount = windowSize//2
print(padAmount)

1


In [7]:
padded_F0 = np.pad(F0, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

In [8]:
padded_F0.shape

(152, 152, 3)

In [9]:
F0_test = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
def padArray(arr, windowSize):
    padAmount = windowSize//2
    return np.pad(arr, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

In [11]:
F0_test.shape

(2, 2, 3)

In [12]:
def printArray(arr):
    for row in arr:
        for e in row:
            print(e, end=" ")
        print("\n")

In [13]:
printArray(F0_test)

[1 2 3] [4 5 6] 

[7 8 9] [10 11 12] 



In [14]:
F0_test.shape

(2, 2, 3)

In [15]:
np.set_printoptions(linewidth=np.inf)

In [16]:
padded_F0_test = padArray(F0_test, 3)

In [17]:
padded_F0_test.shape

(4, 4, 3)

In [18]:
printArray(padded_F0_test)

[0 0 0] [0 0 0] [0 0 0] [0 0 0] 

[0 0 0] [1 2 3] [4 5 6] [0 0 0] 

[0 0 0] [7 8 9] [10 11 12] [0 0 0] 

[0 0 0] [0 0 0] [0 0 0] [0 0 0] 



In [19]:
print(padAmount)

1


In [20]:
i, j = 1, 1
window = padded_F0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
printArray(window)

[0 0 0] [0 0 0] [0 0 0] 

[0 0 0] [1 2 3] [4 5 6] 

[0 0 0] [7 8 9] [10 11 12] 



In [21]:
for i in range(padAmount, len(padded_F0_test)-padAmount):
    for j in range(padAmount, len(padded_F0_test[0])-padAmount):
        window = padded_F0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
        printArray(window)
        print("NEXT WINDOW")
    

[0 0 0] [0 0 0] [0 0 0] 

[0 0 0] [1 2 3] [4 5 6] 

[0 0 0] [7 8 9] [10 11 12] 

NEXT WINDOW
[0 0 0] [0 0 0] [0 0 0] 

[1 2 3] [4 5 6] [0 0 0] 

[7 8 9] [10 11 12] [0 0 0] 

NEXT WINDOW
[0 0 0] [1 2 3] [4 5 6] 

[0 0 0] [7 8 9] [10 11 12] 

[0 0 0] [0 0 0] [0 0 0] 

NEXT WINDOW
[1 2 3] [4 5 6] [0 0 0] 

[7 8 9] [10 11 12] [0 0 0] 

[0 0 0] [0 0 0] [0 0 0] 

NEXT WINDOW


# TESTING SPECTRAL DISTANCE

In [35]:
import cv2
import numpy as np

In [36]:
windowSize = 3
padAmount = windowSize//2
spatImp = 150

### Padding array

In [24]:
def padArray(arr, windowSize):
    padAmount = windowSize//2
    return np.pad(arr, [(padAmount, padAmount), (padAmount, padAmount), (0, 0)], mode='constant', constant_values=0)

### Print cell

In [25]:
def printArray(arr):
    for row in arr:
        for e in row:
            print(e, end=" ")
        print("\n")

In [26]:
F0_test = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
padded_F0_test = padArray(F0_test, windowSize)

In [27]:
C0_test = np.array([[[1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1]]])
padded_C0_test = padArray(C0_test, windowSize)

In [64]:
C1_test = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
padded_C1_test = padArray(C1_test, windowSize)

### Spectral Distance

In [62]:
for i in range(padAmount, len(padded_F0_test)-padAmount):
    for j in range(padAmount, len(padded_F0_test[0])-padAmount):
        F0_window = padded_F0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
        C0_window = padded_C0_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]
        C1_window = padded_C1_test[i-windowSize//2:i+windowSize//2+1, j-windowSize//2:j+windowSize//2+1]

        x, y, z = F0_window.shape

        print(f"Window around point ({i}, {j})")

        # Spectral Difference/Distance
        spectral_difference_window = F0_window - C0_window
        spectral_distance_window = 1/(abs(spectral_difference_window) + 1.0)
        
        # Temporal Difference/Distance
        temp_difference_window = C1_window - C0_window
        temp_distance_window = 1/(abs(temp_difference_window) + 1.0)
        # print(temp_distance_window.shape)
    
        # Spatial Distance
        coord = np.sqrt((np.mgrid[0:windowSize,0:windowSize]-windowSize//2)**2)
        spat_dist = np.sqrt(((0-coord[0])**2+(0-coord[1])**2))
        rel_spat_dist = spat_dist/spatImp + 1.0 # relative spatial distance
        rev_spat_dist = 1/rel_spat_dist # relative spatial distance reversed
        rev_spat_dist = np.repeat(rev_spat_dist[:,:,np.newaxis], z, axis=2)


3 3 3
Window around point (1, 1)
[0.99065997 0.99065997 0.99065997] [0.99337748 0.99337748 0.99337748] [0.99065997 0.99065997 0.99065997] 

[0.99337748 0.99337748 0.99337748] [1. 1. 1.] [0.99337748 0.99337748 0.99337748] 

[0.99065997 0.99065997 0.99065997] [0.99337748 0.99337748 0.99337748] [0.99065997 0.99065997 0.99065997] 



## Temporal Distance